name: Generate PlantUML
on:
  push:
    paths:
      - '**.puml' # Only runs when you change a .puml file
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Essential for accessing your files

      - name: Generate SVG
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: diagrams/ # Folder where your .puml files live
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to push images back
